In [128]:
import numpy as np

In [129]:
arr1=np.array([1,2,3,4])          #ye array bana kar dega 
print(arr1)

[1 2 3 4]


In [130]:
type(arr1)                     #type chk krne k liye

numpy.ndarray

In [131]:
arr1.ndim                       #isne btaya ki ye 1 dimension hai

1

In [132]:
arr2=np.array([[1,2,3],[3,4,5]])          #ye array bana diya 2 dimension ka
print(arr2)

[[1 2 3]
 [3 4 5]]


In [133]:
arr2.size               #size matlab how many elements are there 

6

In [134]:
arr2.shape             # 2 rows hain 3 coloumn

(2, 3)

In [135]:
arr2.dtype              #type int32

dtype('int32')

In [136]:
mx1=np.ones((3,3),dtype=int)          #dtype int na krne par float m dega values.
print(mx1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [137]:
mx2=np.zeros((3,3))
print(mx2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [138]:
mx3=np.empty((3,3))
print(mx3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [139]:
arr3=np.arange(1,13,1)                   #start,end,steps
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
np.linspace(1,6,5,dtype=int)

array([1, 2, 3, 4, 6])

In [141]:
arr4=arr3.reshape(2,6)
print(arr4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [142]:
arr4.ravel()                   #single dimension mai change kia , we can use flatten too

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [143]:
arr4.transpose()


array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# mathematical operations

In [144]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [145]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [146]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [147]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [148]:
arr1.max()

9

In [149]:
arr1.min()

1

In [150]:
arr1.argmax()            #index max value ka

8

In [151]:
arr1.max(axis=0)                #0 row k liye

array([7, 8, 9])

In [152]:
arr1.max(axis=1)                   #1 column k liye

array([3, 6, 9])

In [153]:
np.sum(arr1)

45

In [154]:
np.sum(arr1,axis=0)        #column ka sum kia hai

array([12, 15, 18])

In [155]:
np.sum(arr1,axis=1)         #row ka sum kia hai

array([ 6, 15, 24])

In [156]:
np.mean(arr1)

5.0

In [157]:
np.median(arr1)

5.0

In [158]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [159]:
np.std(arr1)          #standard divison

2.581988897471611

In [160]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [161]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [162]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# array slicing

In [163]:
mx=np.arange(1,10).reshape(3,3)
print(mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [164]:
mx[0,0]

1

In [165]:
mx[1,1]                  #python mai index 0 se strat hota hai

5

In [166]:
mx[0]

array([1, 2, 3])

In [167]:
mx[:,0]

array([1, 4, 7])

In [168]:
mx[:,0:1]         #2d mai show karega

array([[1],
       [4],
       [7]])

In [169]:
mx[1:4,1:4]

array([[5, 6],
       [8, 9]])

In [170]:
mx.itemsize         #output byte mai hai 32/8=4

4

# array conctination and split

In [171]:
np.concatenate((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [173]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

# split

In [174]:
arr3=np.arange(1,10).reshape(3,3)
print(arr3)

np.split(arr3,3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [175]:
np.split(arr3,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

# random sampling

In [176]:
import random

In [177]:
np.random.random(1)

array([0.90259848])

In [178]:
np.random.random((3,3))

array([[0.44994999, 0.61306346, 0.90234858],
       [0.09928035, 0.96980907, 0.65314004],
       [0.17090959, 0.35815217, 0.75068614]])

In [179]:
np.random.randint(1,4)

2

In [180]:
np.random.randint(1,4,(3,3))

array([[1, 2, 3],
       [1, 1, 3],
       [1, 1, 1]])

In [181]:
np.random.rand(3)

array([0.65310833, 0.2532916 , 0.46631077])

In [182]:
np.random.rand(3,3)         #0 se 1 k beech values milti hain

array([[0.24442559, 0.15896958, 0.11037514],
       [0.65632959, 0.13818295, 0.19658236],
       [0.36872517, 0.82099323, 0.09710128]])

In [183]:
np.random.randn(3,3)

array([[ 0.6536186 , -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316]])

In [184]:
x=[1,2,3,4,5]
np.random.choice(x)

3

In [185]:
np.random.permutation(x)            #order can be random

array([2, 1, 5, 3, 4])

# string operations,comparison,information

In [186]:
name="Krishna Mohan Tiwari"
str1="learning python NumPy"

In [187]:
np.char.add(name,str1)

array('Krishna Mohan Tiwarilearning python NumPy', dtype='<U41')

In [188]:
np.char.lower(name)

array('krishna mohan tiwari', dtype='<U20')

In [189]:
np.char.upper(str1)

array('LEARNING PYTHON NUMPY', dtype='<U21')

In [190]:
np.char.center(str1,90)

array('                                  learning python NumPy                                   ',
      dtype='<U90')

In [191]:
np.char.split(name)

array(list(['Krishna', 'Mohan', 'Tiwari']), dtype=object)

In [192]:
np.char.splitlines("hello \n python")

array(list(['hello ', ' python']), dtype=object)

In [193]:
str2="kmt"
str3="hola"

In [194]:
np.char.join([":","/"],[str2,str3])

array(['k:m:t', 'h/o/l/a'], dtype='<U7')

In [195]:
np.char.replace(name,"Tiwari","tiwary")

array('Krishna Mohan tiwary', dtype='<U20')

In [196]:
np.char.equal(str2,str3)

array(False)

In [197]:
np.char.count(name,'i')

array(3)

In [200]:
np.char.find(name,'Mohan')

array(8)

In [204]:
c=np.mod(arr1,2)==0
print(c)

[[False  True False]
 [ True False  True]
 [False  True False]]
